### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by TommyLemon** [bimohxh/jsonon#1]
这是我改的效果嘿嘿

让接口和文档见鬼去吧！后端零用时开发接口，前端/客户端 定制返回JSON的内容和结构！
http://apijson.cn/

**Comment by bimohxh** [comment]
@TommyLemon  哈哈 不错，有想法

**Comment by TommyLemon** [comment]
@bimohxh  没找到你的联系方式，可以加个QQ吗？1184482681， 一起交流探讨😄
