### ISSUE TITLE
Add copy function

### ISSUE THREAD

**Issue by krait8064** [bimohxh/jsonon#2]
Can you add two buttons to copy the json string of the two main part of the view near position of  expand all and collapse all  button?It's easy to do and so useful

**Comment by bimohxh** [comment]
Ctrl A + Ctrl c can copy the json，I don't think this is  needed

**Comment by TommyLemon** [comment]
@bimohxh Ctrl A will select all text of the whole web page, including the left input text.

**Comment by bimohxh** [comment]
put your cusor in left textarea will just copy the json string

**Comment by krait8064** [comment]
> put your cusor in left textarea will just copy the json string

How about add copy button in right textarea,buddy!

**Comment by krait8064** [comment]
> put your cusor in left textarea will just copy the json string

How about add the same ctrl+A in right textarea,buddy!

**Comment by TommyLemon** [comment]
@bimohxh O I C, and U R right
I need this function is just because the output does not equal the input on http://apijson.org/.
I'll deal with this problem by myself.

**Comment by TommyLemon** [comment]
@krait8064 You can format the left json text, and then copy the text.

**Comment by krait8064** [comment]
> @krait8064 You can format the left json text, and then copy the text.

I mean the same way of CTRL+A in right area to select right text not the whole page

**Comment by TommyLemon** [comment]
@krait8064 But you'll get the same copied text in this way

**Comment by krait8064** [comment]
Yep,but programmers are always lazier,then our product get better

**Comment by TommyLemon** [comment]
@krait8064 It does make sense

**Comment by bimohxh** [comment]
@krait8064  why you need to copy the right area content, this just the same as left

**Comment by bimohxh** [comment]
Why I hate the copy feature is that, this is not always work in browser, I will more believe Ctr C + Ctr V

**Comment by krait8064** [comment]
> Why I hate the copy feature is that, this is not always work in browser, I will more believe Ctr C + Ctr V

Come on,buddy! U a the superman and u can make it! 0.0

**Comment by krait8064** [comment]
> Why I hate the copy feature is that, this is not always work in browser, I will more believe Ctr C + Ctr V

It's just useful when
