### ISSUE TITLE
右侧格式化之后的区域全选问题

### ISSUE THREAD

**Issue by qiushui95** [bimohxh/jsonon#3]
Ctrl+A选中的是整个网页内容
不是我想要的格式化之后的结果
使用的是chorme

**Comment by bimohxh** [comment]
为什么不复制左侧的呢。左侧是文本域。右侧是视图

**Comment by qiushui95** [comment]
左侧本来就是我复制进去的  我赋值他干嘛。。。。。右侧是格式化之后的，我才需要啊

**Comment by TommyLemon** [comment]
@qiushui95  可以点“美化”按钮格式化左侧的JSON

**Comment by bimohxh** [comment]
@qiushui95 主要是这里说的是全选，全选的话直接美化之后，CTRL+A 左侧的数据就行了
