### ISSUE TITLE
json format loss the accuracy

### ISSUE THREAD

**Issue by cc-alvin** [bimohxh/jsonon#4]
if I format the following string,it will not work as what I want.
`
{
    "Hello": 1051665002546245634
}
`
It will show 
`
{
"Hello": 1051665002546245600
}
`
not 
`
{
"Hello": 1051665002546245634
}
`

Please ,thanks

**Comment by bimohxh** [comment]
this seems a bug for JSON.parse
```js
JSON.parse('{ "Hello": 1051665002546245634 }')
```

**Comment by bimohxh** [comment]
the main problem is at 1051665002546245634  is a big number. you can't show this even in a varaible. just try `Number.MAX_SAFE_INTEGER`

**Comment by TommyLemon** [comment]
@bimohxh U R right.
@zc1024 Try quoting this number to make it right.
{ "Hello": "1051665002546245634" }
